services:
  python-yolo-service:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: python-yolo-service

    ports:
      - "${PYTHON_YOLO_PORT:-8000}:8000"

    environment:
      - PYTHON_YOLO_PORT=${PYTHON_YOLO_PORT:-8000}
      - STREAM_URL=${STREAM_URL:-0}
      - SPRING_URL=${SPRING_URL:-http://localhost:8080}
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}

    # Permisos de hardware para acceder a la cámara en Raspberry Pi
    privileged: true

    devices:
      - /dev/video0:/dev/video0
      - /dev/vchiq:/dev/vchiq

    volumes:
      - /run/udev:/run/udev:ro

    group_add:
      - video

    networks:
      - cut_ia_network

    restart: on-failure

networks:
  cut_ia_network:
    external: true